services:
  pgsql:
    image: postgres:17
    container_name: pgsql17
    restart: always
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432" 
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data
      - ./pgsql/postgresql.conf:/etc/postgresql/postgresql.conf
    
    