services:
  casserver:
    image: apereo/cas
    container_name: casserver
    environment:
      - SERVER_SSL_ENABLED=false
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped